/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
* No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
* applicable laws, including copyright laws. 
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
* OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
* LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
* INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
* ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability 
* of this software. By using this software, you agree to the additional terms and conditions found by accessing the 
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2020 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

/***********************************************************************************************************************
*  File Name    : RL78G23_100GLG_IICA0_Original_EEPROM_24C32_WR_Demo.c
*  Description  : Main Program
*  Creation Date: 2025-10-02
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "r_smc_entry.h"

int main (void);

uint8_t g_Rx_buff[16];              /* 接收缓冲区                   */
uint8_t g_Tx_buff[16];              /* 发送缓冲区                   */
uint8_t write_data[12];             /* 写入数据缓冲区（2字节地址+10字节数据）*/
uint8_t success;
uint8_t sladr8 = 0xAE;
uint8_t compare_ok;

#define SUCCESS ( 0x00 )

int main(void)
{
    uint16_t i;                         /* loop counter for subloop     */
    uint8_t status;
    uint8_t addr_buf[2];                /* 地址缓冲区（支持16位地址）    */
    EI();

    /*------------------------------------------------------
         EEPROM写入：写入10个字节测试数据
    ------------------------------------------------------*/
        
    // 准备写入数据：地址(0x0008) + 10字节数据
    write_data[0] = 0x00;           /* 地址高字节                   */
    write_data[1] = 0x08;           /* 地址低字节（写入地址0x08）    */
        
    // 填充测试数据
    for(i = 0; i < 10; i++)
    {
        write_data[i + 2] = 0x20 + i;  /* 测试数据：0x20, 0x21, ... 0x29 */
    }
    
    // 写入地址+数据（共12字节）
    status = R_Config_IICA0_Master_Send(sladr8, write_data, 12,100);

    if (SUCCESS == status)
    {
    		R_BSP_SoftwareDelay(5, BSP_DELAY_MILLISECS);
    }

    /*------------------------------------------------------
        EEPROM读取：读取刚写入的10个字节并对比
    ------------------------------------------------------*/

    // 第1步：Dummy Write - 设置EEPROM内部地址指针
    addr_buf[0] = 0x00;             /* 地址高字节                   */
    addr_buf[1] = 0x08;             /* 地址低字节（读取地址0x08）    */

    status = R_Config_IICA0_Master_Send(sladr8, addr_buf, 2,100);
    R_BSP_SoftwareDelay(1, BSP_DELAY_MILLISECS);

    if (SUCCESS == status)
    {
    		status = R_Config_IICA0_Master_Receive(sladr8, g_Rx_buff, 10,100);

    	            if (SUCCESS == status)
    	            {
    	                // 等待读取完成（发送STOP条件）
    	            		R_BSP_SoftwareDelay(5, BSP_DELAY_MILLISECS);

    	                if (SUCCESS == status)
    	                {
    	                    // 读取成功，对比写入和读取的数据
    	                    compare_ok = 1;  /* 假设对比成功 */

    	                    for(i = 0; i < 10; i++)
    	                    {
    	                        if (g_Rx_buff[i] != write_data[i + 2])  /* 跳过地址部分 */
    	                        {
    	                            compare_ok = 0;  /* 数据不匹配 */
    	                            break;
    	                        }
    	                    }

    	                    if (compare_ok)
    	                    {
    	                        // 数据对比成功
    	                        // 可以在这里设置指示灯或其他成功标志
    	                    		success = 0x88;
    	                    }
    	                    else
    	                    {
    	                        // 数据对比失败
    	                        // 可以在这里设置错误指示
    	                    }
    	                }
    	            }
    }


    while(1)
    {
    	    R_BSP_SoftwareDelay(5, BSP_DELAY_MILLISECS);

    }


}
